# 400 error will be thrown above this limit.
max_locations_per_request: 10000

# CORS header. Should be None for no CORS, '*' for all domains, or a url with
# protocol, domain, and port ('https://api.example.com/'). Default is null.
access_control_allow_origin: null

datasets:
  - name: eudem25m
    path: data/eudem/
    filename_epsg: 3035
    filename_tile_size: 1000000
