version: "3.7"
services:
  xccup-elevation-api:
    container_name: "xccup-elevation-api"
    restart: unless-stopped

    volumes:
      - "../data:/app/data:ro"
    expose:
      - 5000
    image: "opentopodata"

    labels:
      traefik.enable: true
      traefik.http.routers.xccup-elevation-api.rule: "Host(`elevation.lurb.org`)"
      traefik.http.routers.xccup-elevation-api.entrypoints: websecure
      traefik.http.routers.xccup-elevation-api.tls.certresolver: myresolver
      traefik.port: 5000
      traefik.docker.network: traefik

networks:
  default:
    external:
      name: traefik
